Update for integration build  (27 changes)  bug 317907: [api] provide support for password prompting  bug 361977: Hide Completed Reviews filter also hides Rule  bug 361979: Only Restore Element command should be visible  bug 361980: Reviewer participant cannot always add a new  bug 361982: NullPointerException when trying to add decision  bug 362016: NPE adding an existing Review group  bug 364478: Creation of a group does not open it some times  bug 364509: NPE retrieving context when attachment creation date  bug 364511: R4Eclipse rule set open when not requested  bug 364621: It shall be possible to regress an anomaly in  bug 364637: Allow not participants to write anomalies (formal  bug 365374: [user] Hide completed reviews by default  bug 366111: R4Eclipse can not remove the project id from a review  bug 367134: Review Navigator label for Comment element should  bug 367136: Decision meeting duration and location cannot  bug 367185: [user] Filter - Hide Completed Reviews - Hides  bug 367209: Time Management - Unable to add the same time value  bug 367215: R4E mail notification with disable participants  bug 367320: R4E navigator view should not open when adjusting  bug 368462: Unable to progress the state of anomalies created at  bug 368607: update Bugzilla repositories to 4.0.3, 3.6.7, and  bug 368784: markup-to-eclipse-help task fails to render cross-references correctly when multipleOutputFiles is specified  bug 368830: fix NPE when releasing request  bug 368873: Hudson standalone tests fail with NoClassDefFoundError  Improve documentation for cross-references  Modifications to address Anomalies raised in Reviews for the last  Revert "ASSIGNED - bug 367861: fields marked as incoming on Eclipse.org that had no changes  https://bugs.eclipse.org/bugs/show_bug.cgi?id=367861"