Update for integration build  (47 changes)  bug 168204: [patch] support bugzilla's usermatchmode for  bug 305782: remove bogus dependencies  bug 317907: [api] provide support for password prompting  bug 351100: fix address of local proxy  bug 351100: fix failing tests for Mylyn 3.7  bug 353236: remove tasks.ui dependency on monitor.ui  bug 355059: [Compatibility] Mylyn's activate task trim is not  bug 356786: fix failing tests  bug 357294: add jsoup bundle to SDK feature  bug 357294: [api] provide API for converting content to wiki markup  bug 359461: move user activity monitoring into a separate bundle  bug 361977: Hide Completed Reviews filter also hides Rule  bug 361979: Only Restore Element command should be visible  bug 361980: Reviewer participant cannot always add a new  bug 361982: NullPointerException when trying to add decision  bug 362016: NPE adding an existing Review group  bug 364155: [api] add a method to retrieve projects in current  bug 364478: Creation of a group does not open it some times  bug 364509: NPE retrieving context when attachment creation date  bug 364511: R4Eclipse rule set open when not requested  bug 364621: It shall be possible to regress an anomaly in  bug 364637: Allow not participants to write anomalies (formal  bug 365374: [user] Hide completed reviews by default  bug 366111: R4Eclipse can not remove the project id from a review  bug 367134: Review Navigator label for Comment element should  bug 367136: Decision meeting duration and location cannot  bug 367185: [user] Filter - Hide Completed Reviews - Hides  bug 367209: Time Management - Unable to add the same time value  bug 367215: R4E mail notification with disable participants  bug 367320: R4E navigator view should not open when adjusting  bug 367525: MediaWiki to Eclipse Help does not honour templateExcludes  bug 368462: Unable to progress the state of anomalies created at  bug 368607: update Bugzilla repositories to 4.0.3, 3.6.7, and  bug 368777: [api] support pre-emptive authentication in  bug 368784: markup-to-eclipse-help task fails to render cross-references correctly when multipleOutputFiles is specified  bug 368830: fix NPE when releasing request  bug 368835: disable log output for org.apache.http.*  bug 368873: Hudson standalone tests fail with NoClassDefFoundError  bug 368912: setup test environment for Hudson 2.2 and 3.0 M0  bug 369421: update to Orbit build I20120121011730 (or later)  bug 369598: NPE when expanding comments in the task editor  bug 369697: fix test failures on Java 1.7  fix standalone test dependencies  Improve documentation for cross-references  Merge remote-tracking branch 'origin/master' into e_4_1_m_3_x  Modifications to address Anomalies raised in Reviews for the last  Revert "ASSIGNED - bug 367861: fields marked as incoming on Eclipse.org that had no changes  https://bugs.eclipse.org/bugs/show_bug.cgi?id=367861"